[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "bayesian-synpop"
dynamic = ["version"]

dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "pgmpy==1.0.0",
    "omegaconf",
    "streamlit",
    "pygraphviz",
]
requires-python = ">=3.12"
authors = [{name = "Yunshuo Tang", email = "551835@mail.muni.cz"}]
description = "Two-layer Bayesian model for synthetic population generation."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["Bayesian network", "synthetic population","simulation based"]

[project.optional-dependencies]
test = ["pytest"]

[tool.pytest.ini_options]
pythonpath = ["src"]
python_files = ["test.py", "test_*.py", "*_test.py"]
testpaths = ["test.py"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["synpop", "synpop.*"]
namespaces = true
[tool.setuptools_scm]
