train:
  raw_h_df: "C:/Users/tang/database/SynPop/synthetic_populations/input/H_sample_5%.xlsx"
  raw_p_df: "C:/Users/tang/database/SynPop/synthetic_populations/input/P_sample_5%.xlsx"
  h_nodes: ["H_motor_v", "H_venr_bike"] # Excluding the count of members even though they might be in the household dataframe 
  p_nodes: ["P_gender", "P_work", "P_education", "driver_license", "prepaid_tickets"] # Exclude the origin age column
  age_col: "P_age"
  age_bin: [-1, 5, 17, 29, 39, 49, 59, 69, 79, float("inf")]
  gender_col: "P_gender"
  h_id_col: "H_ID"
  score: "aic-d"
  composition_cols: {"adults":"H_persons_1899","minors":"H_persons_0617","kids":"H_persons_0005"} # In the order of adults, minor and children, one or more cols can be supplied

synthesis:
  num_households: 1500
  pool_multiplier: 50
  max_retries: 10
  random_seed: 42
  max_workers: 8
  p_data_include_kid: false

calibration:
  max_iterations: 100
  tolerance: 1.0e-6
  p_marginals: {
    "SEXE": {"1": 2042494, "2": 2210748}, 
    "CS1": {"1": 1469, "2": 103500, "3": 611888, "4": 557518, "5": 595924, "6": 304869, "7": 628168, "8": 1449906}, 
    "DIPL_15": {"A": 971873, "B": 500578, "C": 620487, "D": 1350186, "Z": 810118}, 
    "EMPL": {"11": 38876, "12": 21212, "13": 8839, "14": 10907, "15": 153798, "16": 1506973, "21": 110790, "22": 68924, "23": 1488, "ZZ": 2331435}, 
    "ETUD": {"1": 1121545, "2": 3131697}, "STAT_CONJ": {"A": 1397063, "B": 2856179}, 
    "age_cate": {"0": 310218, "1": 654153, "2": 707364, "3": 653433, "4": 592718, "5": 517486, "6": 403933, "7": 232916, "8": 181021}
    }
  h_marginals: {
    "TYPL": {"1": 18799, "2": 437277, "3": 14317, "4": 5943, "5": 1545, "6": 7737}, 
    "VOIT": {"0": 296715, "1": 156547, "2": 31430, "3": 14159}
    }
  p_attributes: ["SEXE", "CS1", "DIPL_15", "EMPL", "ETUD", "STAT_CONJ"]
  h_attributes: ["TYPL", "VOIT"]
  kwargs:
    method: "logit" #'linear', 'raking', or 'logit'
    bounds: (0.001,50.0)  # The bounds for logit method. Defaults to (0.1,5.0).
    alpha: 1e-3 # For CrossEntropy 
paths:
  output_dir: "output"
  dags_dir: "${paths.output_dir}/dags"

  person_dag: "${paths.dags_dir}/person"
  household_dag: "${paths.dags_dir}/household"
  
  bundle_file: "${paths.output_dir}/bn_bundle.pkl"
